version: "3"

services:
  root:
    build: .
    command: bash
    tty: true
    stdin_open: true
    environment:
      DISPLAY: $DISPLAY
      HOME: /home/pkg
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./pkg:/home/pkg
    network_mode: "host"